### ISSUE TITLE
Comments miss dependent: :destroy

### ISSUE THREAD

**Issue by HouzuoGuo** [SUSE/hackweek#104]
Hello!

Yesterday I attempted to create a new project, the submission failed with a server error, but then it actually appeared in New Project list ("Scalability improvement for running tiedot database on SMP systems").

https://hackweek.suse.com/projects/680

Unfortunately the link does not work, the server says "something went wrong".

**Comment by HouzuoGuo** [comment]
Looks like it is now fixed, thanks!

**Comment by hennevogel** [comment]
Not really fixed. It was a dangling comment.
