### ISSUE TITLE
Replace broken sunspot/solr

### ISSUE THREAD

**Issue by hennevogel** [SUSE/hackweek#106]
The deployment is :boom: all the time. Especially restarting the service almost always fails. solr is also very keen on dying random deaths and in general it's a way to fat solution for our small 'search' problem. Additionally the sunspot community is pretty inactive.

We need to find something lightweight, supported.

**Comment by kirushik** [comment]
We will need a standalone instance of search engine in production for most of the gems.
Both https://github.com/pat/thinking-sphinx (based on Sphinx) and https://github.com/ankane/searchkick (based on Logstash) seem to be well-maintained alternatives.

I can start with this task. Which search engine is easier to provide on our production server?

**Comment by kirushik** [comment]
Studying the docs a little bit more, I'd really like to see us taking Sphinx and thinking-sphinx approach.

**Comment by hennevogel** [comment]
@kirushik in the meantime I had to disable sunspot completely because I couldn't get it to stay up after the update to the last version. Java issues an all. sphinx is available on the machine so thinking-sphinx is a go
