### ISSUE TITLE
Use tags for navigation and filtering

### ISSUE THREAD

**Issue by kirushik** [SUSE/hackweek#107]
We are already storing tags in our database.
We should really use them for limiting browsing and search to a certain tag or an intersection of tags. (When I'm searching `[GUI]` and `[C++]`, I'm searching for projects in both categories simultaneously, not in one or the either.)

It can be implemented with an additional control on the browse page; we already have a drop-down for tags, with autocompletion; we still need to forbid unrecognized tags from there during the search.

**Comment by hennevogel** [comment]
Done in #740 now
