### ISSUE TITLE
Have Random list of projects

### ISSUE THREAD

**Issue by kirushik** [SUSE/hackweek#109]
On the projects browsing page, we should add 'Random' tab, where the projects will be ordered differently on each load.
We should limit it's output to something comprehensible (7, maybe 10 items), and provide a button 'More random stuff' which will update the list with some new random projects.

Of course that random output should respect episodes and tags filters.
We should also hide the button 'More random' if there are no more projects with current filters, but this should be considered as an optional 'nice to have' feature.

**Comment by hennevogel** [comment]
Why do I want to see random stuff? :-)

**Comment by kirushik** [comment]
To just have an unopinionated overview of what we have to offer.
That's typically very good complimentary for ratings and search — ratings are clearly favoring top items (and thus hurting everything else), and searches are useless until you're looking for something specific.

**Comment by cornelius** [comment]
One use case, where I would love to see this feature, is projection of random projects on the wall during Hack Week events (e.g. an opening party). For this "random list with automatic refresh" would do the trick.

**Comment by kirushik** [comment]
@cornelius You seem to talk about a little bit different feature, but I like yours even more than mine. Maybe you can update the issue definition to match your expectations?

**Comment by cornelius** [comment]
I added a new issue: #113

**Comment by hennevogel** [comment]
By now we show popular projects
