### ISSUE TITLE
AJAXifying the main page

### ISSUE THREAD

**Issue by kirushik** [SUSE/hackweek#111]
We shouldn't really re-render and reload the full page for just switching tabs.
I bet I can implement AJAX calls for those links, which will just replace the contents, not the full webpage.
(And this will certainly work better with the caching from #110 )

**Comment by kirushik** [comment]
Also AJAXifyed as-you-type search results would be really great.

**Comment by namangupta01** [comment]
Hey! May i work on this issue!
