### ISSUE TITLE
New front page

### ISSUE THREAD

**Issue by cornelius** [SUSE/hackweek#116]
It would be nice to have a new front page for Hack Week 12. I would imagine something simple collecting  some of the relevant things we already have. It could be a brief statement what Hack Week is, the latest news entries, the most popular project, and some links to the list of projects and creation of a new project.

**Comment by cornelius** [comment]
Maybe we could also reuse the Hack Week 12 poster somehow:

![Hack Week 12 Poster](http://paste.opensuse.org/view/raw/26079326)

**Comment by hennevogel** [comment]
I've added a front page in #148
