### ISSUE TITLE
trying to update a project fails

### ISSUE THREAD

**Issue by bs-github** [SUSE/hackweek#1181]
I can not update my project page.
Error message on pressing Update Project:

```
5
(0_0)
0
We're sorry, but something went wrong.
How about you file an issue on github and let us know what you did? That would be AWESOME!

Head back Home
```

I tried to update this page: https://hackweek.opensuse.org/22/projects/open-source-firmware-for-ev-chargers-using-the-esp32-chip-autoaid-slash-en-plus-slash-evsedo/edit

**Comment by bs-github** [comment]
I found the char actually provoking the error to be: 🥳

**Comment by hennevogel** [comment]
Duplicate of #585
