### ISSUE TITLE
Substring search is not working on the production.

### ISSUE THREAD

**Issue by kirushik** [SUSE/hackweek#123]
Our SearchController should be falling back to wildcard search if no lemmatized matches found: https://github.com/SUSE/hackweek/blob/master/app/controllers/search_controller.rb#L4-L9

But this doesn't happen at the moment, most probably because of some quirk in production Sphinx configuration (missing indices, non-generating trigrams...)

This feature should be working, as it is especially valuable in searching users.

**Comment by hennevogel** [comment]
It's disabled because there are conflicting settings. At least building the index told me that. Have to investigate...

**Comment by kirushik** [comment]
Can you successfully run the search tests in the vagrant environment?
Maybe that's just me having some weirdly-configured but working setup? And the search fails for everybody else?

**Comment by kirushik** [comment]
I've just tried search specs on an fresh vagrant installation — they seem to pass.
But it really bother me the there is possibly no real improvement over the sunspot in stability and ease of deployment...

**Comment by hennevogel** [comment]
sorry I haven't found the time to investigate yet :( maybe tomorrow...

**Comment by hennevogel** [comment]
Works for me now...
