### ISSUE TITLE
How do I develop without vagrant?

### ISSUE THREAD

**Issue by hennevogel** [SUSE/hackweek#125]
As we now have a config/database.yml in the repo that is vagrant specific there is no way to develop without vagrant anymore...

**Comment by kirushik** [comment]
It would be still impossible to develop without running `searchd`, as we are using ThinkingSphinx indexer callbacks in our models. Rails won't save `Project` or `User` models without Sphinx, and Sphinx can't talk to SQlite.

So the answer is — if you want to develop locally, you need to have MySQL and Sphinx installed and ready. You can have a look into `bootstrap.sh` to figure out how to install them.X

You can still use SQlite for tests, as I've stubbed out the realtime indexer for specs (you need to tag spec with `:search` to turn indexing back on, this tag is excluded by default.)

**Comment by hennevogel** [comment]
But I will either commit config/database.yml or it will get overwritten each time I pull, reset and whatnot. Can't you use some other file for the 'static' vagrant specific setup?

**Comment by kirushik** [comment]
Maybe we can store database details in ENV and provide a predefined set of such variables to Vagrant box with something like https://github.com/gosuri/vagrant-env.

Or maybe we should just sacrifice that turnkey start feeling, and add `database.yml` back to `.gitignore`, providing vagrant database config as a `database.yml.vagrant` file.

Which way would you prefer?

**Comment by hennevogel** [comment]
What would both mean for setting up the development environment?

**Comment by hennevogel** [comment]
@kirushik any news on this?

**Comment by kirushik** [comment]
Yes, sorry for that. Here is the fix.
I will provide the more 12-factory solution for the config during (or shortly after) the hackweek.

**Comment by hennevogel** [comment]
JFYI: we already use figaro
