### ISSUE TITLE
error 500 on users/73

### ISSUE THREAD

**Issue by tampakrap** [SUSE/hackweek#135]
https://hackweek.suse.com/users/73 this gives error 500

**Comment by kirushik** [comment]
@bkutil It's most probably this error: https://errbit-opensuse.herokuapp.com/apps/52448dcab9289e000a000005/problems/55251b6f8a3f8c43d400024a

As it's somehow related to the decorators, can you please take a look?

**Comment by bkutil** [comment]
https://github.com/SUSE/hackweek/pull/136 should fix this

**Comment by bkutil** [comment]
Ok, the fix is incomplete. Still does not work for search results. Sorry for overlooking this.

**Comment by kirushik** [comment]
Should be fixed for now (with #136 being deployed), so I'm closing this bug.
