### ISSUE TITLE
Using unicode explodes the application

### ISSUE THREAD

**Issue by AdamMajer** [SUSE/hackweek#1360]
I've tried to use `:smile:` in my description and that exploded its size as per https://github.com/SUSE/hackweek/issues/1359. So then I used the unicode character for it -- `😄` and I got 

![image](https://github.com/SUSE/hackweek/assets/1211498/fc455731-652f-4948-8042-6a456c861fd8)

**Comment by hennevogel** [comment]
Duplicate of #585
