### ISSUE TITLE
Can't create any comments....

### ISSUE THREAD

**Issue by AdamMajer** [SUSE/hackweek#1371]
https://hackweek.opensuse.org/projects/port-neuvector-zero-trust-security-functions-to-host-slash-vm/comments

![image](https://github.com/SUSE/hackweek/assets/1211498/4c7f44a5-2771-4a2a-af4c-273c312428cc)

**Comment by hennevogel** [comment]
found the problem (opensuse datacenter move removed outbound internet access). working on it.

**Comment by hennevogel** [comment]
should work again, sorry for the inconvenience...
