### ISSUE TITLE
Make like-project icon more visible

### ISSUE THREAD

**Issue by bgeuken** [SUSE/hackweek#139]
It took me a while to find it and it seems I am not the only one.

To me one reason for that is that one wouldn't expect it next to the user name, but close to the project itself. So either on the right side of the project title or next to the join project icon.

**Comment by hennevogel** [comment]
Patches welcome ;-)

**Comment by bgeuken** [comment]
I am already checking the current 'issues' for something I can do...

For this particular one I don't dare to do any change until someone with an eye for design said how it should look like;-)

**Comment by bgeuken** [comment]
Thinking about it, we could have a "I like this button" next to the "Join this project" one (also green and big). As we both now, there is always room for adding another button:P

**Comment by hennevogel** [comment]
No movement since a while and people like projects all the time...
