### ISSUE TITLE
Add a profile field for location

### ISSUE THREAD

**Issue by srett** [SUSE/hackweek#144]
So, this is my first hackweek. I'm currently in Beijing and checked out the projects before the week started. I was hoping I could just see which projects have members that would attend the hackweek at the Beijing Office, but to no avail.

Sure you can always collaborate via IRC, the comments, etc., but imo it's much more fun to work together in person. So how about adding a profile field where you can state which Suse office you will be at (or just select "I'm at home" or similar)? Maybe also indicate who is a Suse employee and who is just visiting? :)

**Comment by kirushik** [comment]
That makes sense. I'd like also to investigate whether we can just extract that data from our iChain profiles, and not bother users with additional fields (which most probably will be simply ignored).

**Comment by thutterer** [comment]
@srett Good idea! And I would suggest not to read this from any [iChain](https://www.novell.com/coolsolutions/feature/2434.html), whatever exactly that was :smile: 
A hacker might not be at the same office in HackWeek than where she usually works from. So trying to be smart and read it from some database might actually be wrong and inflexible.

An optional static dropdown with SUSE office locations (incl. "home office") would already be a nice improvement.

A cooler solution might be including a openstreetmap (or similar), allow people to pinpoint their location and have smart auto-suggestions for office locations). In the DB we would save the geo coordinates.

**Comment by biswesh456** [comment]
@thutterer I would love to work on it. Can I be guided on the list of SUSE office locations so that I can put it on the drop down menu?

**Comment by biswesh456** [comment]
I have added the drop down box in the project page only if the user is a member of that project.
Now I want to know how do we show the list of places where the members would be?
Should I make a pr showing my progress till now?

**Comment by biswesh456** [comment]
The location of a user gets shown when we choose a user who is participating in the project.
Hence we can go to a project, click on a hacker and see the location of that hacker for that project

Is this design fine?

![location change](https://user-images.githubusercontent.com/24248795/36343892-5cf74058-1438-11e8-94e1-97278716f84b.gif)

**Comment by thutterer** [comment]
Hi Biswesh, haven't seen your updates here over the weekend :beach_umbrella: :relaxed: 
I'll mark myself as reviewer for this PR but it'll take me a bit to find the time to give it a proper review.
But a first scroll-over your changes looks good :+1:

**Comment by biswesh456** [comment]
Thanks @thutter. Waiting for your review ☺️.

**Comment by DavidKang** [comment]
Handle in PR #264
