### ISSUE TITLE
Change URL on the github project (for any ADMIN, no code is necessary)

### ISSUE THREAD

**Issue by pedrocarr** [SUSE/hackweek#1440]
Hi, looking around the project I noticed that the actual URL linked to the project is not working 

- _http://hackweek.suse.com/_ might be _https://hackweek.opensuse.org/_
<img width="296" alt="Screenshot 2024-01-11 at 10 45 16" src="https://github.com/SUSE/hackweek/assets/45405776/dd291775-6f16-42c4-8f96-1a8d7c456f27">

**Comment by hennevogel** [comment]
thanks for the report @pedrocarr 💐
