### ISSUE TITLE
can not login with opensuse

### ISSUE THREAD

**Issue by colyli** [SUSE/hackweek#152]
My opensuse ID is colyli, when I use it to log into https://hackweek.suse.com, I come to a page with information: We're sorry, but something went wrong. How about you file an issue on github and let us know what you did? That would be AWESOME!

It seems other people does not have problem with log in. 

Also I tried to log into https://features.opensuse.org with my opensuse account and pass, it works, then I go to https://hackweek.suse.com, I encounter same error message: We're sorry, but something went wrong. How about you file an issue on github and let us know what you did? That would be AWESOME!

**Comment by hennevogel** [comment]
The search daemon died. Fixed
