### ISSUE TITLE
We're sorry, but something went wrong

### ISSUE THREAD

**Issue by dzedro** [SUSE/hackweek#153]
Getting message "We're sorry, but something went wrong" when using search field

**Comment by AdamMajer** [comment]
Also, trying to create a project....

**Comment by mauromorales** [comment]
Same for me when I tried to sign up

**Comment by keichwa** [comment]
+1

**Comment by plusky** [comment]
Or when I try to edit project

**Comment by peterph** [comment]
Very likely an intermittent infrastructure thing - at least search already works again.

**Comment by keichwa** [comment]
ok, now it worked for me...

I think it would be fair if you'd announce the involvement of an external server somewhere...

**Comment by peterph** [comment]
@keichwa it seems to be a default HTTP 500 internal server error page.

**Comment by hennevogel** [comment]
The search daemon died. Restarted
