### ISSUE TITLE
markdown comment section rendering does not regard newlines

### ISSUE THREAD

**Issue by okurz** [SUSE/hackweek#154]
## observation
Comment content like
```
L0: now comes a code section
L1: ```
L2: do this
L3: do that
L4: ```
```

gets rendered into something like

> now comes a code section *do this* *do that*

## expected result

> now comes a code section
> ```
> do this
> do that
> ```

**Comment by hennevogel** [comment]
We are not doing anything special, just call [redcarpet](https://github.com/vmg/redcarpet). Please take your issue there...

**Comment by okurz** [comment]
I looked through all the redcarpet issues and didn't find anything related but only issues that look more sophisticated, i.e. the code blocks certainly work in redcarpet in general.

I am pretty sure this is a problem on how the content is formatted within hackweek or missing options to redcarpet, please check again.
