### ISSUE TITLE
Markdown "list" not working

### ISSUE THREAD

**Issue by wnereiz** [SUSE/hackweek#159]
The list is marked with * in markdown language, but it's not working when I creating the project. I have to use html for it.

**Comment by hennevogel** [comment]
List are working fine for me.

![screenshot from 2017-02-21 12-49-48](https://cloud.githubusercontent.com/assets/514785/23163793/4373f2dc-f834-11e6-93ac-76a628aaa460.png)

Can you paste me your markdown snippet that isn't?

**Comment by thutterer** [comment]
Stale issue ... I just tried myself and `*` works well. I'm guessing @wnereiz did'nt have a empty line above the list (which would not be valid markdown syntax).

Can we close this, @wnereiz ?
