### ISSUE TITLE
Could not create a new project and get error message when I would like to check my profile

### ISSUE THREAD

**Issue by alcho** [SUSE/hackweek#160]
* When I would like to create a new project , the error message show up list below:
--- start ---
1 error prohibited this project from being saved:
Originator can't be blank
--- end ---

* In https://hackweek.suse.com/users/me
Get message list below:
--- start ---
We're sorry, but something went wrong.
How about you file an issue on github and let us know what you did? That would be AWESOME!
--- end ---

* If I would like to join some porject , then show this message list below :
--- start ---
The change you wanted was rejected.
Maybe you tried to change something you didn't have access to.
--- end ---

**Comment by alcho** [comment]
My account is "acho" in hackweek.suse.com .

**Comment by hennevogel** [comment]
Somehow your username was different than the one that came from access manager. fixed
