### ISSUE TITLE
Host is not reboot save

### ISSUE THREAD

**Issue by lrupp** [SUSE/hackweek#175]
After applying the latest kernel updates, the machine did not fully recover. Please fix and make sure that all services are up and running again - even after a reboot of the machine.

Thanks!

**Comment by thutterer** [comment]
Not really a issue of this repo but of server provisioning. 
@hennevogel Is this issue solved or tracked somewhere else?
Then I would close it here.

**Comment by hennevogel** [comment]
the deployment runs on passenger. apache starts in the default runlevel. don't know what else to do...

**Comment by lrupp** [comment]
Site note: As this ticket is nearly a year old, I guess we should simple look again once the machine get's rebooted once more...  ;-)
