### ISSUE TITLE
Upgrade to rails 5

### ISSUE THREAD

**Issue by bgeuken** [SUSE/hackweek#188]
The hackweek tool is currently running on rails 4.2. Would be nice to update it to rails 5.1.

I would recommend starting with reading the release notes (see links below). They also provide an upgrade guide from Rails 4.2 to rails 5.0 and rails 5.0 to rails 5.1.

Rails 5.0 release notes: http://guides.rubyonrails.org/5_0_release_notes.html
Rails 5.1 release notes: http://guides.rubyonrails.org/5_1_release_notes.html

**Comment by DavidKang** [comment]
Handled in PR #311
