### ISSUE TITLE
Can't verify CSRF token authenticity for creating project

### ISSUE THREAD

**Issue by AnkushMalik** [SUSE/hackweek#191]
User is directed to error page upon saving project.

![](https://screenshotscdn.firefoxusercontent.com/images/a4869988-941d-4ae9-b3db-f25a87bc9c54.png)

**Comment by hennevogel** [comment]
Probably after you have *previewed* it?

**Comment by AnkushMalik** [comment]
yeah but even when we don't preview the description project doesnt get saved as it looks for originator_id (blank) :/
