### ISSUE TITLE
Fix Bundler/OrderedGems offence

### ISSUE THREAD

**Issue by DavidKang** [SUSE/hackweek#203]
In our rubocop_todo we need to fix Bundler/OrderedGems offence to make Rubocop happy and also to have a Gemfile ordered.

For more information about this cop, please visit  [Bundler/OrderedGems](http://rubocop.readthedocs.io/en/latest/cops_bundler/#bundlerorderedgems)

**Comment by namangupta01** [comment]
@DavidKang May i try this issue?

**Comment by DavidKang** [comment]
@namangupta01, sure! :+1:

**Comment by Ana06** [comment]
@namangupta01 I think this issue is too easy for you, why don't you take something more difficult?

**Comment by namangupta01** [comment]
@Ana06 sure! :)

**Comment by hennevogel** [comment]
Fixed in #665
