### ISSUE TITLE
Fix  Layout/CommentIndentation offences

### ISSUE THREAD

**Issue by DavidKang** [SUSE/hackweek#207]
In our rubocop_todo we need to fix Layout/CommentIndentation offence to make Rubocop happy and also to have the comments well indented :smile_cat: 

For more information about this cop, please visit [Layout/CommentIndentation](http://rubocop.readthedocs.io/en/latest/cops_layout/#layoutcommentindentation)

**Comment by AnkushMalik** [comment]
i would like to work on this

**Comment by DavidKang** [comment]
@AnkushMalik, sure! :+1:
