### ISSUE TITLE
Fix Layout/EmptyLinesAroundBlockBody offences

### ISSUE THREAD

**Issue by DavidKang** [SUSE/hackweek#208]
We are cleaning up our rubocop_todo file :see_no_evil: and we want to fix `Layout/EmptyLinesAroundBlockBody` offences.

For more information about this cop visit [Layout/EmptyLinesAroundBlockBody](http://rubocop.readthedocs.io/en/latest/cops_layout/#layoutemptylinesaroundblockbody).

**Comment by rishabhptr** [comment]
@DavidKang Can I work on it?

**Comment by DavidKang** [comment]
@rishabhptr, go ahead :+1:
