### ISSUE TITLE
User#edit is incomplete

### ISSUE THREAD

**Issue by AnkushMalik** [SUSE/hackweek#211]
A user can only go to his edit page by passing the path in the address bar. there should be a btn in user#show accessible to that user only.
also in edit form there isn't any field for the name of the user
![screenshot-2018-2-21 suse hack week 1](https://user-images.githubusercontent.com/13421233/36450351-a69338ca-16b3-11e8-8c49-cadfb4c96de7.png)
.

**Comment by hennevogel** [comment]
This only would make sense if we would not use `devise_ichain_authenticatable` because this shifts user management to the login proxy...

All installations of this app are using `devise_ichain_authenticatable`...

**Comment by AnkushMalik** [comment]
ok :+1: ,closing issue
