### ISSUE TITLE
Mobile Navbar error

### ISSUE THREAD

**Issue by AnkushMalik** [SUSE/hackweek#214]
Navbar is mobile view is not working properly. Both dropdowns are opened.

![screenshot-2018-2-21 suse hack week 2](https://user-images.githubusercontent.com/13421233/36453337-c09982ec-16bd-11e8-9166-88b95937304f.png)

Desired functionality would be similar to [this](https://bootsnipp.com/snippets/x8eBB).

**Comment by hennevogel** [comment]
Works for me by now
