### ISSUE TITLE
[production][comments#create] ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by bgeuken** [SUSE/hackweek#269]
comments#create threw this 4 times
<pre>
ActionController::InvalidAuthenticityToken: ActionController::InvalidAuthenticityToken
</pre>
[https://hackweek.suse.com/projects/bugzilla-sync-for-taiga/comments](https://hackweek.suse.com/projects/bugzilla-sync-for-taiga/comments)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620cb02dc71fa0092000007/problems/5b293bb490b0a6000b909e79)

**Comment by bgeuken** [comment]
For what it's worth, I wasn't able to reproduce this. So this might be solved with the newest code base.

@hennevogel Do you know by any chance which version / git revision hackweek.suse.com is running on?

**Comment by hennevogel** [comment]
@bgeuken  on 251d2569c084aceeade14ee817cd8e14dcf2c8f0

**Comment by hennevogel** [comment]
Does not happen anymore
