### ISSUE TITLE
Improve project page design

### ISSUE THREAD

**Issue by Ana06** [SUSE/hackweek#289]
the distribution of the things in the [project page](https://hackweek.suse.com/17/projects/jetpad-online-collaborative-text-editor) looks strange:

![image](https://user-images.githubusercontent.com/16052290/42283385-8ffca4b6-7fa9-11e8-8265-862916459353.png)

Too empty, and the projects are in side really compressed.

I think we can find a better design for this page. :wink: Maybe it is a good idea to have at the button a dedicated section for the related projects.

**Comment by hennevogel** [comment]
@AnkushMalik can you look into this?
