### ISSUE TITLE
"Create a project" page displays outdated header box

### ISSUE THREAD

**Issue by dragotin** [SUSE/hackweek#290]
On the "Create a project" page an outdated header is displayed, as visible on this screenshot:

![screenshot_20180704_162039](https://user-images.githubusercontent.com/1070214/42283537-0c1f0980-7faa-11e8-8bf0-35fb4d4b2d21.png)

Note that the Episode on top is right, but the yellow box refers to Hack Week 0x10.

**Comment by dragotin** [comment]
Same for the start page actually.

**Comment by hennevogel** [comment]
It's a feature. Just click the button :-)

**Comment by dragotin** [comment]
Is it also a feature that the text in the box does not make sense at all? How can that be changed?
