### ISSUE TITLE
[production][projects#leave] AbstractController::DoubleRenderError: Render and/or redirect were called multiple times in this ...

### ISSUE THREAD

**Issue by DavidKang** [SUSE/hackweek#299]
projects#leave threw this 1 times
<pre>
AbstractController::DoubleRenderError: Render and/or redirect were called multiple times in this action. Please note that you may only call render OR redirect, and at most once per action. Also note that neither redirect nor render terminate execution of the action, so if you want to exit an action after redirecting, you need to do something like &quot;redirect_to(...) and return&quot;.
</pre>
[https://hackweek.suse.com/17/projects/github-graphql-v4/leave](https://hackweek.suse.com/17/projects/github-graphql-v4/leave)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620cb02dc71fa0092000007/problems/5b4317392e9695001416a004)

**Comment by hennevogel** [comment]
did not happen for years...
