### ISSUE TITLE
[production][projects#advance] AASM::InvalidTransition: Event 'advance' cannot transition from 'invention'. 

### ISSUE THREAD

**Issue by DavidKang** [SUSE/hackweek#300]
projects#advance threw this 0 times
<pre>
AASM::InvalidTransition: Event &#39;advance&#39; cannot transition from &#39;invention&#39;. 
</pre>
[https://hackweek.suse.com/17/projects/github-graphql-v4/advance](https://hackweek.suse.com/17/projects/github-graphql-v4/advance)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620cb02dc71fa0092000007/problems/5b43174d2e9695000616a001)

**Comment by hennevogel** [comment]
did not happen for months...
