### ISSUE TITLE
Adding link in comment, markdown doesn't render properly

### ISSUE THREAD

**Issue by ktsamis** [SUSE/hackweek#307]
Adding this to the comment section in the page somehow adds emojis to the link? I write this:
```
```https://build.opensuse.org/project/show/home:ktsamis:branches:home:bergmannf```

```
and this is how the preview shows it:
```
https://build.opensuse.org/project/show/home![add-emoji](https://assets-cdn.github.com/images/icons/emoji/ktsamis.png)branches![add-emoji](https://assets-cdn.github.com/images/icons/emoji/home.png)bergmannf
```

Adding it as an external link as well makes it resolve like that and it is a 404 of course. You can see the [invalid link here](https://hackweek.suse.com/projects/connect-to-matrix-dot-org-via-weechat)

**Comment by hennevogel** [comment]
@AnkushMalik I believe that is your work :-)

**Comment by DavidKang** [comment]
Handled in #595
