### ISSUE TITLE
Issue with Docker and ThinkingSphinx

### ISSUE THREAD

**Issue by AnkushMalik** [SUSE/hackweek#346]
- bootstrap: 
<img width="574" alt="screen shot 2018-07-24 at 7 25 52 pm" src="https://user-images.githubusercontent.com/13421233/44780747-48d78100-aba0-11e8-8a83-847d59fdacfe.png">

___

- bootstrap command runs without any problem but when I start the development enviroment I face following error : 
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/13421233/44780934-bedbe800-aba0-11e8-8d04-8d130f853867.png">

I have stopped/deleted container with docker prune and tried  to set up enviroment multiple times but facing this same issue.

Note: There was no /sphinx directory created in my project.

**Comment by hennevogel** [comment]
What OS do you run docker on?

**Comment by AnkushMalik** [comment]
macOS High Sierra

**Comment by hennevogel** [comment]
Hm sounds like this happens when a crash left behind a pid?

http://sphinxsearch.com/forum/view.html?id=9235

Please try if cleaning up helps...

```
rm -rf sphinx
rm -rf db/sphinx/development
rm -f config/application.yml config/development.sphinx.conf config/database.yml config/secrets.yml
rm -rf tmp/*
rm log/development.*
```

**Comment by AnkushMalik** [comment]
Thank you, now I can successfully run the enviroment now. 😼 
but now there is another minor issue :
<img width="401" alt="image" src="https://user-images.githubusercontent.com/13421233/44855726-57e62e00-ac89-11e8-9e64-ae8a70bcb8f2.png">

log:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/13421233/44855879-a72c5e80-ac89-11e8-854f-0fa7ac039255.png">

but for the time being, I can comment the ts callbacks in my models. :-)

**Comment by hennevogel** [comment]
You should rebase to get 59562644b196195055f5f520591f4a90cc927a63
