### ISSUE TITLE
[production][users#show] Mysql2::Error: Unknown column 'comments.user_id' in 'where clause': SELECT `co[Truncated]

### ISSUE THREAD

**Issue by hennevogel** [SUSE/hackweek#438]
users#show threw this 16 times
<pre>
Mysql2::Error: Unknown column &#39;comments.user_id&#39; in &#39;where clause&#39;: SELECT `co[Truncated]
</pre>
[https://hackweek.suse.com/users/hennevogel](https://hackweek.suse.com/users/hennevogel)"

[See this exception on Errbit](https://errbit-opensuse.herokuapp.com/apps/5620cb02dc71fa0092000007/problems/5ca762acc405120011d4aee1)

**Comment by coolo** [comment]
It's up to 19609 times by now
