### ISSUE TITLE
Feature: speak with project creator before joining 

### ISSUE THREAD

**Issue by MalloZup** [SUSE/hackweek#443]
Desc :

(I'm abstracting the implementation details etc) but speaking as user. 

The feature would be : in the webui, if a collaborator want to join a project XX, he she can't join directly as now it is,  but instead she he should ask to the maintainer creator of project, (with a email chat etc) to add him her to projects . 
 It would be something similar to github maintership, adding collaborator

At first glance this feature can sound restrictive but it isn't. To me it would rather favorize communication upfront, and also avoiding that people join projects without knowning what to do or sync each other. Also it would enable people to speak more about their projects and also to think a rough plan about what and if help it needed for the project.  From the creator side and the commaborator side

Example : I create a vague project with a new Lang and I call it 'learn XX lang or create bot xx'. So maybe other people join directly without asking and also we do something in same project without really collaborating. 

 With a kind of protection for joining the project, people could known what it might be necessary to do for the project as collaborator etc, and also I as creator will learn more when I explain the project in details etc.

**Comment by hennevogel** [comment]
People joining a project signal that they want to collaborate. If that doesn't spark any communication between the people in a project I fail to see how blocking them from joining would. I also don't want to put this decision in front of project creators without helping them to make it, how should we?

I recognize the *"problem"* you describe as a missing guidance on how you can organize a *"hackweek project"*. Giving people sensible defaults for this sounds like a better way to spark collaboration to me.

**Comment by MalloZup** [comment]
@hennevogel  thx for answer. Right it could be that templates are better for maybe mitigating it. :rocket:

**Comment by hennevogel** [comment]
I guess it boils down to: How would we organize a "hackweek project"?

**Comment by hennevogel** [comment]
You first! :wink:

**Comment by hennevogel** [comment]
> How would we organize a "hackweek project"?

This is now addressed with #683. Feel free to extend the text.
