### ISSUE TITLE
Logged In user are prompted to login again

### ISSUE THREAD

**Issue by b10n1k** [SUSE/hackweek#485]
When i pass my credentials to the login page https://hackweek.suse.com/users/ichain_sign_in the page appears again. the only indication that someone is logged in is his avatar. 
I think it should redirect to somewhere else and maybe display a notification. 
in case that you dont realise that you logged in and try again using wrong credentials the page correctly informs you that something is wrong but it is confusing as you are already logged in

**Comment by hennevogel** [comment]
Yeah the local access manager proxy is supposed to redirect you another page but this seems to not work anymore. An issue is filed for it but I wouldn't hold my breath...

If I find the time (maybe next hackweek) I'm going to switch to okta...

**Comment by hennevogel** [comment]
This is fixed now in the login proxy.

**Comment by okurz** [comment]
That did not seem to work for me. I went to hackweek.suse.com/ , was not logged in. Clicked "Sign In". Was successfully logged in – top right shows my avatar and there is a flash message about "Hack Week 19" – but the page is again https://hackweek.suse.com/users/ichain_sign_in

**Comment by hennevogel** [comment]
gah, it worked yesterday.

**Comment by hennevogel** [comment]
works again, was something on my side sorry.

**Comment by okurz** [comment]
don't break it again then ;)

**Comment by hennevogel** [comment]
yes boss!
