### ISSUE TITLE
Not able to access https://hackfest.microfocus.net/

### ISSUE THREAD

**Issue by atapas** [SUSE/hackweek#562]
![image](https://user-images.githubusercontent.com/3633137/71717106-00d40880-2e3d-11ea-867f-d7bc01358cf1.png)

**Comment by DavidKang** [comment]
Hi @atapas, could you explain it a little bit? thanks :slightly_smiling_face:

**Comment by yansamue** [comment]
I am getting the identical error screen that @atapas is seeing above.

**Comment by hennevogel** [comment]
sorry but we have nothing to do with this installation. you have to file a rio ticket
