### ISSUE TITLE
Searching anything causes a HTTP 500 error

### ISSUE THREAD

**Issue by srinidhibs** [SUSE/hackweek#655]
Steps to reproduce:
===============
  * Head over to https://hackweek.suse.com
  * Enter a string - e.g., "yast" or "y2profiler" - in the search box and hit the <kbd>Enter</kbd> key.
  * You will receive a 500 error message.

Additional information:
=================
I don't know if this is related or not, but when I followed a link to a HackWeek project from a Google search - https://hackweek.suse.com/19/projects/speed-up-installation - even then, I received a HTTP 500 error.

**Sidebar**:
I'm unable to login to hackweek.suse.com hence, I cannot confirm whether the problem is seen only when I am not logged in.

**Comment by bmwiedemann** [comment]
I tested that it also happens when logged in.

**Comment by hennevogel** [comment]
fixed
