### ISSUE TITLE
SSL Certificate of hackweek.suse.com has expired

### ISSUE THREAD

**Issue by srinidhibs** [SUSE/hackweek#656]
Steps to reproduce:
===============
  * Access https://hackweek.suse.com
  * Instead of opening the landing page of HackWeek site, the browser will prompt you about expired certificate.

In Firefox, it says:

> Websites prove their identity via certificates, which are valid for a set time period. The certificate for hackweek.suse.com expired on 11/12/2020.
>  
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE
> 

In Chromium / Google Chrome, it says:

> This server could not prove that it is hackweek.suse.com; its security certificate expired 2 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Friday, November 13, 2020. Does that look right? If not, you should correct your system's clock and then refresh this page.

**Comment by NAVNAV123** [comment]
Yep, same to me.

**Comment by bmwiedemann** [comment]
I fixed it.
