### ISSUE TITLE
Logout has no effect

### ISSUE THREAD

**Issue by rsimai** [SUSE/hackweek#666]
Click on my avatar then "Log out" (https://hackweek.suse.com/users/ichain_sign_out) has no effect for me, I stay logged in and can continue to navigate and work on projects.

**Comment by hennevogel** [comment]
This is something for eng-infra, can you report it there please?

**Comment by rsimai** [comment]
For the records: https://infra.nue.suse.com/SelfService/Display.html?id=186028
