### ISSUE TITLE
Database container crashes when initializing the database

### ISSUE THREAD

**Issue by dmarcoux** [SUSE/hackweek#703]
This is from the output I got when executing `docker-compose up --build`:

```bash
Starting hackweek_db_1 ... done
Creating hackweek_hackweek_1 ... done
Attaching to hackweek_db_1, hackweek_hackweek_1
db_1        | Initializing database
db_1        | 
db_1        | FATAL ERROR: Could not find /usr/bin/my_print_defaults
db_1        | 
db_1        | If you compiled from source, you need to either run 'make install' to
db_1        | copy the software into the correct location ready for operation.
db_1        | If you don't want to do a full install, you can use the --srcdir
db_1        | option to only install the mysql database and privilege tables.
db_1        | 
db_1        | If you are using a binary release, you must either be at the top
db_1        | level of the extracted archive, or pass the --basedir option
db_1        | pointing to that location.
db_1        | 
db_1        | The latest information about mysql_install_db is available at
db_1        | https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
hackweek_db_1 exited with code 1
```

I reverted the changes of https://github.com/SUSE/hackweek/commit/dfd8252c8bdc38cb7646caaa00e720ecaf52fe7d for the password in `config/database.yml.example` and all changes in `docker-compose.yml` and I could start the development environment.

**Comment by hennevogel** [comment]
```
Starting hackweek_db_1 ... done
Creating hackweek_hackweek_1 ... done
Attaching to hackweek_db_1, hackweek_hackweek_1
```

Sounds like you're using the old container image with the new settings? :smile:

**Comment by dmarcoux** [comment]
I've removed everything all Docker images and containers to start from scratch. I ended up getting the same error as above in the `hackweek_db_1` container. See the complete logs after running the command `docker-compose run --rm hackweek bundle exec rake dev:bootstrap` as explained in the [README](https://github.com/SUSE/hackweek#hack-it).

Logs: https://paste.opensuse.org/12687584

Something is broken.

**Comment by eduardoj** [comment]
I see two errors there:
```
16. Step 3/16 : RUN echo 'solver.allowVendorChange = true' >> /etc/zypp/zypp.conf;     zypper ar -f https://download.opensuse.org/repositories/openSUSE:/infrastructure:/hackweek/openSUSE_Leap_15.2/openSUSE:infrastructure:hackweek.repo;     zypper --gpg-auto-import-keys refresh
17.  ---> Running in 7ebfbda64de9
18. File '/repositories/openSUSE:/infrastructure:/hackweek/openSUSE_Leap_15.2/openSUSE:infrastructure:hackweek.repo' not found on medium 'https://download.opensuse.org/'
```

... and:
```
39. 'libmysqld-devel' not found in package names. Trying capabilities.
```

I could reproduce the errors, too.

**Comment by eduardoj** [comment]
@dmarcoux:

> I've removed everything all Docker images and containers to start from scratch. I ended up getting the same error as above in the `hackweek_db_1` container. See the complete logs after running the command `docker-compose run --rm hackweek bundle exec rake dev:bootstrap` as explained in the [README](https://github.com/SUSE/hackweek#hack-it).
> 
> Logs: https://paste.opensuse.org/12687584
> 
> Something is broken.

Maybe you are using configuration files wich were generated long time ago. This configuration files will be generated again with the `dev:bootstrap` rake task. Please try again with these steps:
- Remove the files: `config/application.yml`, `config/database.yml` and `config/secrets.yml`.
- Remove all docker containers.
- Remove all docker images.
- `docker-compose run --rm hackweek bundle exec rake dev:bootstrap`

**Comment by eduardoj** [comment]
@hennevogel:

> Hmmmmm. I guess I have removed the repository? Added again. Please try

That fixed the repository error, thanks.

I can setup the development environment without problems.
