### ISSUE TITLE
site not rendering

### ISSUE THREAD

**Issue by ories** [SUSE/hackweek#718]
1) log in
2) hit https://hackweek.suse.com/projects/newest?page_size=58
3) pick a project and comment on it
4) hit back 2x to get to 2)
5) get served plain html
6) refresh renders the site from 2)

![Screen Shot 2021-03-08 at 8 56 01 AM](https://user-images.githubusercontent.com/3490626/110345717-1e29d700-7fec-11eb-900a-c4d532cfbd75.png)

works in Safari, doesn't work in FF (on MacOS) - originally reported on FF on Windows

**Comment by mlnoga** [comment]
Originally reported on (the horror) **Chrome** on Windows.

**Comment by hennevogel** [comment]
This was a deployment fallout. We are operating on a very tight budget and sometimes are a bit more brute with this. Sorry :smile:
