### ISSUE TITLE
episode: no error or warning when using a non-existing episode id

### ISSUE THREAD

**Issue by bgeuken** [SUSE/hackweek#89]
e.g. https://hackweek.suse.com/31/projects/archived

**Comment by hennevogel** [comment]
What would you expect?

**Comment by thutterer** [comment]
@bgeuken Can we close this? Or can you suggest a change?

**Comment by bgeuken** [comment]
>  hennevogel commented on Feb 21, 2017
> What would you expect?

Hard to answer after 3 years:wink:
Looking at the url from the description I would say it would be nice to make it visible that this is showing all projects, not a particular hackweek.
IIRC, back then the episode handling was quite messy and one could end up with a state where it's unclear which hackweek is checked out.
Seems this no issue anymore.

**Comment by bgeuken** [comment]
@thutterer 
> @bgeuken Can we close this? Or can you suggest a change?

Yes, let's close it. Sorry for the late response, Seems I missed the github notification.
