### ISSUE TITLE
Error 500 when loading project page

### ISSUE THREAD

**Issue by pevik** [SUSE/hackweek#896]
It looks any project page fails with error 500, e.g.
https://hackweek.opensuse.org/20/projects/devops-training-in-bangalore
https://hackweek.opensuse.org/20/projects/test-mainline-kernel-on-an-older-qualcomm-soc-msm89xx-explore-mainline-kernel-qualcomm-mainlining

**Comment by hennevogel** [comment]
fixed! forgot to start the searchd. sorry for the noise.

**Comment by hennevogel** [comment]
https://sentry.io/share/issue/4681268b7ecf488d93f881495adf02ee/#threads
