### ISSUE TITLE
User joined twice in project

### ISSUE THREAD

**Issue by bgeuken** [SUSE/hackweek#94]
https://hackweek.suse.com/projects/256

**Comment by thutterer** [comment]
Old issue. Can you still reproduce this? @bgeuken

**Comment by hennevogel** [comment]
@thutterer click on the link?

**Comment by AnkushMalik** [comment]
I also encountered this bug but the exact steps for reproducing it are unknown. It seems like it happens only when the user is also the organiser of that event .

**Comment by bgeuken** [comment]
IIRC, this happened when double clicking the join button. It tried this now and got an exception due to "InvalidAuthenticationToken".

But it's still possible to join a project multiple times. I am working on a patch...
